### ISSUE TITLE
Show any fees associated with classes

### ISSUE THREAD

**Issue by ryanhugh** [ryanhugh/searchneu#13]
You have to pay a fee to take some classes at NEU. Ex: https://wl11gp.neu.edu/udcprod8/bwckschd.p_disp_detail_sched?term_in=201810&crn_in=17822

Lets show this in Search NEU!

**Comment by edward-shen** [comment]
If anyone wants to do this, I think this is one of the features where we could objectively leave out of a class description if there aren't any associated fees.

Most classes won't need this, so for most users, they won't ever find this useful if it just says ("None").

**Comment by ryanhugh** [comment]
Completed by @NEUDitao !
