### ISSUE TITLE
Add support for Course Attributes/NU Path

### ISSUE THREAD

**Issue by ryanhugh** [ryanhugh/searchneu#14]
Some classes satisfy different NU Path/NU core requirements. Lets show this information in Search NEU!

Example: 
https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=201810&subj_code_in=PSYC&crse_numb_in=1101

**Course Attributes**: 
NUpath Natural/Designed World, NU Core Social Science Lvl 1, NUpath Societies/Institutions, UG College of Science 

Lets let users filter classes by this info too (#1).

**Comment by bernhardtj** [comment]
http://www.northeastern.edu/rasala/nucore/dashboard.html
scrape this thing?

**Comment by ryanhugh** [comment]
I was thinking we should scrape the Course Attributes on Banner (the link in the first post). That should have(?) all the information about which classes satisfy which requirements in NU Path and we are already hitting those pages to scrape other pieces of info too. 

Let me know if you are interested in working on this or any other feature/bug on searchneu :)

**Comment by edward-shen** [comment]
Dashboard has been moved to https://www.northeastern.edu/core/dashboard/

**Comment by edward-shen** [comment]
Hey would you look at that:
https://www.northeastern.edu/core/_external/coredata.txt

**Comment by edward-shen** [comment]
Looks like it's actively updated too and parse-able!

**Comment by mukundwagh** [comment]
Hey, I would like to work on this, as discussed in the meeting.

**Comment by ryanhugh** [comment]
All yours! :D

**Comment by ryanhugh** [comment]
This issue is current open for anyone to work on

**Comment by NEUDitao** [comment]
can I call dibs?

**Comment by ryanhugh** [comment]
Sure! This one involves some scraping tweaks and some front end stuff!

**Comment by NEUDitao** [comment]
Finished in #71
