### ISSUE TITLE
Clarify searching for subjects

### ISSUE THREAD

**Issue by ryanhugh** [ryanhugh/searchneu#17]
When you search for a subject on the site (eg `CS` or `Math`) all the classes in that subject will come up, in order. When this happens, lets tell the user that this is happening. We could add a string under the search box that says something like:  
  
### Showing all 53 classes in Computer Science.

**Comment by NEUDitao** [comment]
# Cheese has claimed this

**Comment by edward-shen** [comment]
Who is cheese? Are you going to work on this? I'm so confused.

**Comment by NEUDitao** [comment]
aren't we facebook friends?

**Comment by edward-shen** [comment]
Ok you are cheese.

**Comment by NEUDitao** [comment]
https://github.com/NEUDitao/searchneu

"working" build (ope is midwest for everything)

**Comment by ryanhugh** [comment]
Completed by @NEUDitao !
