### ISSUE TITLE
IE11?

### ISSUE THREAD

**Issue by ryanhugh** [ryanhugh/searchneu#18]
The site dosen't work in IE 11. When someone goes to the site in IE11 it crashes with:

```
TypeError: Unable to get property '__reactInternalInstance$fetqc23p89dh' of undefined or null reference
File https://searchneu.com/0-53c629509336448ef50b.js line 1 col 70380 in getClosestInstanceFromNode
File https://searchneu.com/0-53c629509336448ef50b.js line 1 col 1543931 in findParent
File https://searchneu.com/0-53c629509336448ef50b.js line 1 col 1544184 in handleTopLevelImpl
File https://searchneu.com/0-53c629509336448ef50b.js line 1 col 232188 in o.perform
File https://searchneu.com/0-53c629509336448ef50b.js line 1 col 1542368 in d.batchedUpdates
File https://searchneu.com/0-53c629509336448ef50b.js line 1 col 85798 in batchedUpdates
File https://searchneu.com/0-53c629509336448ef50b.js line 1 col 1545234 in d.dispatchEvent
```

Is it possible to make the site work in IE11 or should we just display a message asking users to use a different browser?

**Comment by edward-shen** [comment]
Possibly related? https://github.com/facebook/react/issues/8031

Guy had an issue with exceptions in his promise handler that causes the same error.

Also, global usage for IE11 is around 3.5% right now, and should even be less for your audience given the population that uses searchneu.

Personally, I think we should be pushing people to (at the very least) Edge.

**Comment by ryanhugh** [comment]
Totally agree. Am totally OK with just disabling the site for IE 11 and putting up a message that asks people to use a different browser (if possible). I'll see if I can pull up some analytics.

**Comment by ryanhugh** [comment]
Browser breakdown on Amplitude over the last 30 days:
![image](https://user-images.githubusercontent.com/5777995/32590338-e7bfea28-c4e7-11e7-889c-f53f015b781f.png)

Browser breakdown on Google Analytics since Sept 4th:
![image](https://user-images.githubusercontent.com/5777995/32590503-b2e8565e-c4e8-11e7-9dbc-5a76a52df106.png)

**Comment by ryanhugh** [comment]
I was able to get access to a computer with IE 11 over break and, like, many different parts of the site were broken. Definitely not worth making it work in IE 11. Changed the code to display an error if the user goes to the site in IE 11. I'l push this to prod sometime over the next couple days. 

Commit: https://github.com/ryanhugh/searchneu/commit/6ca491c86af7e61edbe13078c97393aa4c585b8a

**Comment by ryanhugh** [comment]
And its live!
