### ISSUE TITLE
Missing Prerequisite

### ISSUE THREAD

**Issue by Unix-Code** [ryanhugh/searchneu#26]
Searched for GAME 3800 for Spring 2018, but it was missing a preqrequisite (GAME 3700):
![image](https://user-images.githubusercontent.com/14129378/32812334-751b0766-c972-11e7-8023-acf599b92271.png)

Some of its prerequisites were parsed (ENGW 1102 or ENGW 1111), but not the complete list.

How it's shown in MyNeu:
![image](https://user-images.githubusercontent.com/14129378/32812318-556375d4-c972-11e7-8c13-d71e169a4a70.png)

**Comment by ryanhugh** [comment]
Thanks for reporting this! The two ENGL classes shouldn't be there because they don't exist, but GAME 3700 should definitely be there. I'll investigate!

**Comment by ryanhugh** [comment]
And its fixed! Refresh the page a couple times if it isn't showing up.
