### ISSUE TITLE
Iron out some stuff with prerequisites for

### ISSUE THREAD

**Issue by ryanhugh** [ryanhugh/searchneu#32]
- [x] Lets sort them by classId and put the ones where the subject matches the same class at the beginning
- [x] Lets figure out some way to only show a few and then have a show more button to see more. Some are pretty long: http://localhost:5000/crim+1100 (especially on mobile)
- [x] Also down to only show prerequisites if there are prerequisites, corequisites if there are corequisites, and prerequisites for if there are prerequisites for to be shown.
- [x] Do we want to separate optional prereqsFor and required prereqsFor?

**Comment by edward-shen** [comment]
Just some more todos, from #29:
Todo:
- [ ] Crack a cold one with the boys
- [ ] Add documentation
- [ ] ~~Refactor code to better represent data~~ unshitcode code.
- [ ] Get Ryan to add more todos.
- [ ] Utilize the `isRequired` argument in `parsePreReqs`. We currently don't do anything with it, and the original goal was to add to optional prereqs if `isRequired` was false, and required prereqs for if `isRequired` was true.
- [ ] Add tests
- [ ] Rank lists by how closely related to the subject of the class they're in.

**Comment by edward-shen** [comment]
For your 3rd bullet, I don't think that's a good idea. I'd rather have it show up as 'None' rather than not showing up at all, because it shows that there isn't a pre/co req, rather than we have the lack of data to show it.

**Comment by ryanhugh** [comment]
Truuuuuueeeeee. Lets do that

**Comment by edward-shen** [comment]
Note: I also fixed it when a class isn't a prerequisite for anything, it properly shows None instead of an empty line.

**Comment by edward-shen** [comment]
First bullet kinda done, the rest of the list is in reverse order and I can't seem to fix that.

**Comment by ryanhugh** [comment]
Are we pretty much done everything here? I'm working on some tests in the refactor branch and am down to hold off on tests until we get that branch in.

**Comment by edward-shen** [comment]
We're still missing documentation, but otherwise yeah!

**Comment by edward-shen** [comment]
Closing for now in favor of #15 and #35.
