### ISSUE TITLE
Not actually made with Rocket

### ISSUE THREAD

**Issue by erikuhlmann** [ryanhugh/searchneu#38]
The footer of the site says
![image](https://user-images.githubusercontent.com/16199912/33085625-27e689ac-ceb3-11e7-8832-43ce0e48ab33.png)
But this looks like it's 100% nodejs, not [Rocket](https://rocket.rs).

**Comment by ryanhugh** [comment]
Guess we'll have to get a Node.js icon!! 😄😄 
This originally came from the footer at https://twofactorauth.org/, but the site has changed a lot since then.

**Comment by erikuhlmann** [comment]
I'd actually recommend rewriting it in Rocket.rs, and also have a Rust frontend with webassembly.

**Comment by edward-shen** [comment]
Looks like Ryan changed this in e856db5.

**Comment by ryanhugh** [comment]
Yup - Just switched it around. Should be in prod soon.
