### ISSUE TITLE
Run ESLint and fix style problems

### ISSUE THREAD

**Issue by edward-shen** [ryanhugh/searchneu#5]
After discussion with @ryanhugh, it would be good if someone could ESLint the repo.

On the offhand that linting the repo does break something, this should be held off until after registration season.

Quick links:
[Current style guide (Modified AirBnB)](https://github.com/ryanhugh/searchneu/blob/master/.eslintrc.js)

**Comment by ryanhugh** [comment]
Working on this now! Am making a bunch of changes in the `refactor` branch and just moved a bunch of them over to the `master` branch. All the JS in the `common` directory should pass ESLint now.

**Comment by edward-shen** [comment]
Implemented in #31. Closing
