### ISSUE TITLE
Prereq missing 

### ISSUE THREAD

**Issue by ryanhugh** [ryanhugh/searchneu#62]
https://searchneu.com/201930/CHEM+5622

"(CHEM 2313 or CHEM 2317) and (ENGW 1102 or ENGW 1111) and CHEM 3431 and CHEM 2331 or"

is currently displayed under the Prerequisites section. That last "or" looks like a bug, lets figure out what is going on there. 

It probably has something to do with the "Graduate Admission REQ" on NEU's site that isn't showing up on Search NEU correctly

**Comment by edward-shen** [comment]
![image](https://user-images.githubusercontent.com/6173958/47451711-70a92680-d796-11e8-848e-87b0dae19f96.png)

Unable to reproduce, I get this as the first result?

**Comment by ryanhugh** [comment]
![image](https://user-images.githubusercontent.com/5777995/47451792-a8b06980-d796-11e8-8839-28f19c892d6a.png)

this is what I am seeing, lol. I'll investigate shortly

**Comment by ryanhugh** [comment]
Well, I can't reproduce it anymore. Not sure what was happening haha
