### ISSUE TITLE
Notifying when seats open up dosen't work in safari

### ISSUE THREAD

**Issue by ryanhugh** [ryanhugh/searchneu#65]
Due to support for Safari 12 being temporarily dropped from Facebook's Send To Messenger button. See the warning at the top of this page. 

https://developers.facebook.com/docs/messenger-platform/discovery/send-to-messenger-plugin/

I'll add a warning to the error message to try using a different browser if you are using safari, and will leave this issue open until this is fixed on Facebook's end.

**Comment by ryanhugh** [comment]
This is fixed on facebooks end

**Comment by ryanhugh** [comment]
Actually, nevermind. Looks like Facebook changed some things but it dosen't work yet. We might need to do something on our end.

**Comment by NEUDitao** [comment]
Seems to work now :o :b::b::b::b::b::b::b::b::b::b::b::b::b::b:

**Comment by ryanhugh** [comment]
Awesomeeeee 🎉
